---
title: "EP25-A Data Analysis"
date: "`r Sys.Date()`"
output: 
  flexdashboard::flex_dashboard:
    vertical_layout: scroll
---

```{r setup, echo = FALSE, include = FALSE}
knitr::opts_chunk$set(
    echo = FALSE,
    include = TRUE,
    fig.align = "center"
)
```

```{r pkg.load, include = FALSE}
pkg_lst <- c(
    "knitr",
    "readODS",
    "dplyr",
    "collapsibleTree",
    "flextable",
    "DT",
    "officedown",
    "officer",
    "ggplot2",
    "plotly",
    "here"
)

lapply(
    pkg_lst,
    library,
    character.only = TRUE
)

setwd(
    paste(
        git = here(),
        project = "stability",
        sep = "/"
    )
)

source("lib_ft.r")
```

```{r include = FALSE}
source("ep25_main.r")
```

Raw Data
================

### 原始資料表
    
```{r}
ep25_report_tab[["raw"]] %>%
    theme_ms() %>%
    align(
        align = "center",
        part = "header"
    ) %>%
    align(
        align = "center",
        part = "body"
    )
```
    
### Scatter Plot

```{r}
ep25_report_fig[["raw"]]
```

Linear Regression
================

### Summary

```{r}
ep25_report_tab[["regression"]] %>%
    theme_ms() %>%
    align(
        align = "center",
        part = "header"
    ) %>%
    align(
        align = "center",
        part = "body"
    )
```

Linear Regression: 負漂移
================

```{r}
ep25_report_fig[["regression lwr"]]
```


Linear Regression: 正漂移
================

### Linear Regression

```{r}
ep25_report_fig[["regression upr"]]
```
