---
title: "EP17-A2 LoQ Data Analysis"
date: "`r Sys.Date()`"
output: 
  flexdashboard::flex_dashboard:
    vertical_layout: scroll
---

```{r setup, echo = FALSE, include = FALSE}
knitr::opts_chunk$set(
    echo = FALSE,
    include = TRUE,
    fig.align = "center"
)
```

```{r pkg.load, include = FALSE}
pkg_lst <- c(
    "knitr",
    "readODS",
    "dplyr",
    "flextable",
    "DT",
    "officedown",
    "officer",
    "ggplot2",
    "plotly",
    "here"
)

lapply(
    pkg_lst,
    library,
    character.only = TRUE
)

setwd(
    paste(
        git = here(),
        project = "analytical_sensitivity_loq",
        sep = "/"
    )
)

source("lib_ft.r")
```

```{r include = FALSE}
source("main_ep17loq.r")
```



Raw Data
================

### 原始資料表

```{r}
ep17loq_report_tab[["raw"]]
```

### Scatter Plot

```{r}
ep17loq_report_fig[["raw"]]
```


Total Error
================

### Summary

```{r}
ep17loq_report_tab[["te"]]
```

### Scatter Plot with %TE by Westgard Model

```{r}
ep17loq_report_fig[["te wgs"]]
```

### Scatter Plot with %TE by RMS Model

```{r}
ep17loq_report_fig[["te rms"]]
```